#ifndef _KRIOL_CNST_HEADER
#define _KRIOL_CNST_HEADER

#define KL_STANDARD_FILE_EXTENSION "kl"

#define KL_STANDARD_COMPILER_NAME "kriol"

#define KL_VERSION_MAJOR 1
#define KL_VERSION_MINOR 3
#define KL_VERSION_STRING \
    "Kriol v" KL_XSTR(KL_VERSION_MAJOR) "." KL_XSTR(KL_VERSION_MINOR)
#define KL_XSTR(x) KL_STR(x)
#define KL_STR(x) #x

#endif // _KRIOL_CNST_HEADER