#ifndef _KRIOL_CNST_HEADER
#define _KRIOL_CNST_HEADER

#define KR_STANDARD_NAME "Kriol"
#define KR_STANDARD_FILE_EXTENSION "kriol"
#define KR_ALTERNATIVE_FILE_EXTENSION "kr"
#define KR_STANDARD_COMPILER_NAME "kriol"

#define KR_VERSION_MAJOR 1
#define KR_VERSION_MINOR 7
#define KR_VERSION_PATCH 8

#define KR_VERSION_STRING \
    KR_STANDARD_NAME " v" KR_XSTR(KR_VERSION_MAJOR) "." \
    KR_XSTR(KR_VERSION_MINOR) "." KR_XSTR(KR_VERSION_PATCH)
#define KR_XSTR(x) KR_STR(x)
#define KR_STR(x) #x

#endif // _KRIOL_CNST_HEADER