name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends flex bison clang-19 llvm-19 llvm-19-dev libgc-dev

      - name: Add LLVM 19 to PATH
        run: echo "/usr/lib/llvm-19/bin" >> $GITHUB_PATH

      - name: Run tests
        run: make clean && make test
