name: CI

on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/test'
    runs-on: ubuntu-26.04

    steps:
      - name: Check permission
        uses: actions/github-script@v8
        with:
          script: |
            const assoc = context.payload.comment.author_association;

            const allowed = [
              'OWNER',
              'MEMBER',
              'COLLABORATOR'
            ];

            if (!allowed.includes(assoc)) {
              core.setFailed(
                `User is not allowed (${assoc})`
              );
            }

      - uses: actions/checkout@v5
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends \
            flex bison clang-20 llvm-20 llvm-20-dev llvm-20-tools lld-20 \
            cmake zlib1g-dev libzstd-dev wasi-libc libclang-rt-20-dev-wasm32

      - name: Add LLVM 20 to PATH
        run: echo "/usr/lib/llvm-20/bin" >> $GITHUB_PATH

      - name: Clone submodules
        run: git submodule update --init

      - name: Run tests
        run: |
          cmake -B build
          cmake --build build --target check
